extends "res://build_vivhite_combat_split_mesh_candidate.gd"

## Cross-component, offline-only assembly for the eight semantic groups.
##
## Real images are copied without pixel or Alpha edits. Missing production art
## is represented by a deliberately loud diagnostic page generated by this
## builder. The result is fail-closed and must never be deployed as a skin.

const SEM_COMMAND := "build-semantic-split-v3"
const OUTPUT_ROOT := "Vivhite/tools/candidates/semantic_split_v3"
const RESOURCE_ROOT := "res://tools/candidates/semantic_split_v3"

const HEAD_ROOT := "Vivhite/tools/candidates/semantic_head_face/head0045_weighted"
const HEAD_JSON := "semantic_head_face.spjson"
const HEAD_ATLAS := "semantic_head_face.spatlas"
const HEAD_PAGE := "semantic_head_face.png"
const BASE_PAGE := "vivhite_combat_split_mesh.png"
const DEATH_PAGE := "vivhite_combat_split_mesh_death.png"

const SEM_OUTPUT_JSON := "semantic_split_v3.spjson"
const SEM_OUTPUT_ATLAS := "semantic_split_v3.spatlas"
const SEM_OUTPUT_DATA := "semantic_split_v3_skeleton_data.tres"
const SEM_OUTPUT_MANIFEST := "candidate.json"
const GRAYBOX_PAGE := "semantic_split_v3_graybox.png"
const FAR_THIGH_PAGE := "semantic_far_thigh_0078.png"
const NEAR_THIGH_PAGE := "semantic_near_thigh_0083.png"

const FAR_THIGH_SOURCE := (
	"assets/vivhite-ironclad/generated/evolink-paid/2026-08-28/"
	+ "0078-split-leg-left-thigh-attachment-attempt-07/output.png"
)
const NEAR_THIGH_SOURCE := (
	"assets/vivhite-ironclad/generated/evolink-paid/2026-08-28/"
	+ "0083-split-leg-right-thigh-attachment-attempt-04/output.png"
)
const EXPECTED_FAR_THIGH_SHA := "da48818eb18918236144a2dd0a186218a9fa1d7c6494ac36075532fadd7b72db"
const EXPECTED_NEAR_THIGH_SHA := "f74ec591dbc2718426af1e3e04562cf6ddcae639367c14e5df23e3cbe78714f7"
const EXPECTED_HEAD_PAGE_SHA := "49c4aff9c17b2b2779b2fb030f850b65c4065341f71622148e22ff4191be51a8"
const EXPECTED_HEAD_JSON_SHA := "55e1e98b8edf6cc89d426e2c4380168761a61ac0ba38e04e2609c58e2b2a19e0"

const FAR_THIGH_SOURCE_START := Vector2(484.8639, 365.2990)
const FAR_THIGH_SOURCE_END := Vector2(320.7268, 899.9329)
const NEAR_THIGH_SOURCE_START := Vector2(447.222300, 307.788079)
const NEAR_THIGH_SOURCE_END := Vector2(596.531765, 697.897262)

const REGION_GRAY_TORSO := "gray_torso_core"
const REGION_GRAY_SKIRT := "gray_coordinated_skirt_group"
const REGION_GRAY_FAR_UPPER := "gray_far_upper_arm"
const REGION_GRAY_FAR_FOREARM := "gray_far_forearm_hand"
const REGION_GRAY_NEAR_UPPER := "gray_near_upper_arm"
const REGION_GRAY_NEAR_FOREARM := "gray_near_forearm_hand"
const REGION_GRAY_FAR_LOWERBOOT := "gray_far_lower_leg_with_boot"
const REGION_GRAY_NEAR_LOWERBOOT := "gray_near_lower_leg_with_boot"
const REGION_FAR_THIGH := "semantic_far_thigh_0078"
const REGION_NEAR_THIGH := "semantic_near_thigh_0083"

const GRAY_REGIONS := {
	REGION_GRAY_TORSO: Rect2i(16, 16, 288, 336),
	REGION_GRAY_SKIRT: Rect2i(320, 16, 320, 288),
	REGION_GRAY_FAR_UPPER: Rect2i(16, 384, 224, 88),
	REGION_GRAY_FAR_FOREARM: Rect2i(256, 384, 288, 120),
	REGION_GRAY_NEAR_UPPER: Rect2i(16, 528, 224, 88),
	REGION_GRAY_NEAR_FOREARM: Rect2i(256, 528, 288, 120),
	REGION_GRAY_FAR_LOWERBOOT: Rect2i(16, 672, 352, 128),
	REGION_GRAY_NEAR_LOWERBOOT: Rect2i(400, 672, 400, 128),
}

const REQUIRED_ANIMATIONS: Array[String] = [
	"idle_loop", "low_health_loop", "relaxed_loop", "attack",
	"attack_heavy", "cast", "hurt", "die",
]
const SEM_REQUIRED_EVENTS: Array[String] = [
	"attack_slash_start", "heavy_slash_start", "cast_eyes_start", "clear_vfx",
]

const PART_ATTACHMENTS := {
	"part_leg_left_thigh": REGION_FAR_THIGH,
	"part_leg_left_lower": REGION_GRAY_FAR_LOWERBOOT,
	"part_leg_left_foot": "",
	"part_leg_right_thigh": REGION_NEAR_THIGH,
	"part_leg_right_lower": REGION_GRAY_NEAR_LOWERBOOT,
	"part_leg_right_foot": "",
	"part_arm_left_upper": REGION_GRAY_FAR_UPPER,
	"part_arm_left_forearm": REGION_GRAY_FAR_FOREARM,
	"part_arm_left_hand": "",
	"part_torso": REGION_GRAY_TORSO,
	"part_skirt": REGION_GRAY_SKIRT,
	"part_arm_right_upper": REGION_GRAY_NEAR_UPPER,
	"part_arm_right_forearm": REGION_GRAY_NEAR_FOREARM,
	"part_arm_right_hand": "",
}

const DEATH_ATTACHMENTS := {
	"death_leg_left_thigh": "death_semantic_far_thigh_0078",
	"death_leg_left_lower": "death_gray_far_lower_leg_with_boot",
	"death_leg_left_foot": "",
	"death_leg_right_thigh": "death_semantic_near_thigh_0083",
	"death_leg_right_lower": "death_gray_near_lower_leg_with_boot",
	"death_leg_right_foot": "",
	"death_arm_left_upper": "death_gray_far_upper_arm",
	"death_arm_left_forearm": "death_gray_far_forearm_hand",
	"death_arm_left_hand": "",
	"death_torso": "death_gray_torso_core",
	"death_skirt": "death_gray_coordinated_skirt_group",
	"death_arm_right_upper": "death_gray_near_upper_arm",
	"death_arm_right_forearm": "death_gray_near_forearm_hand",
	"death_arm_right_hand": "",
}


func _initialize() -> void:
	var args := OS.get_cmdline_user_args()
	if args.is_empty():
		args = PackedStringArray([SEM_COMMAND])
	if args[0] in ["-h", "--help", "help"]:
		print("Usage: godot --headless --path tools/art --script res://candidates/semantic_split_v3/build_semantic_split_v3_candidate.gd -- %s [--output-root PATH]" % SEM_COMMAND)
		quit(0)
		return
	if args[0] != SEM_COMMAND:
		quit(_fail("Unknown command: %s" % args[0]))
		return
	var options := _parse_options(args)
	if options.is_empty() and args.size() > 1:
		quit(2)
		return
	var output_root := _absolute_path(str(options.get("output-root", OUTPUT_ROOT)))
	if not _build_candidate(output_root):
		quit(_fail(_last_error))
		return
	quit(0)


func _build_candidate(output_root: String) -> bool:
	_last_error = ""
	if output_root.replace("\\", "/").contains("/Vivhite/Vivhite/skins/ironclad"):
		return _set_error("Research candidate may not target the runtime skin: %s" % output_root)
	var head_root := _absolute_path(HEAD_ROOT)
	var inputs := {
		"head_json": head_root.path_join(HEAD_JSON),
		"head_atlas": head_root.path_join(HEAD_ATLAS),
		"head_page": head_root.path_join(HEAD_PAGE),
		"base_page": head_root.path_join(BASE_PAGE),
		"death_page": head_root.path_join(DEATH_PAGE),
		"far_thigh": _absolute_path(FAR_THIGH_SOURCE),
		"near_thigh": _absolute_path(NEAR_THIGH_SOURCE),
	}
	for label: String in inputs:
		if not FileAccess.file_exists(str(inputs[label])):
			return _set_error("Missing %s input: %s" % [label, inputs[label]])
	if FileAccess.get_sha256(str(inputs.head_page)).to_lower() != EXPECTED_HEAD_PAGE_SHA:
		return _set_error("Frozen head0045_weighted packed page changed")
	if FileAccess.get_sha256(str(inputs.head_json)).to_lower() != EXPECTED_HEAD_JSON_SHA:
		return _set_error("Frozen head0045_weighted Spine JSON changed")
	if FileAccess.get_sha256(str(inputs.far_thigh)).to_lower() != EXPECTED_FAR_THIGH_SHA:
		return _set_error("0078 far-thigh source changed")
	if FileAccess.get_sha256(str(inputs.near_thigh)).to_lower() != EXPECTED_NEAR_THIGH_SHA:
		return _set_error("0083 near-thigh source changed")
	var far_image := _load_rgba(str(inputs.far_thigh), "0078 far thigh")
	var near_image := _load_rgba(str(inputs.near_thigh), "0083 near thigh")
	if far_image.is_empty() or near_image.is_empty():
		return false
	if far_image.get_size() != Vector2i(832, 1248):
		return _set_error("0078 must retain its native 832x1248 canvas")
	if near_image.get_size() != Vector2i(1024, 1024):
		return _set_error("0083 must retain its native 1024x1024 canvas")

	var skeleton_value = JSON.parse_string(FileAccess.get_file_as_string(str(inputs.head_json)))
	var atlas_value = JSON.parse_string(FileAccess.get_file_as_string(str(inputs.head_atlas)))
	if not skeleton_value is Dictionary or not atlas_value is Dictionary:
		return _set_error("Could not parse frozen head candidate")
	var skeleton: Dictionary = (skeleton_value as Dictionary).duplicate(true)
	_patch_skeleton(skeleton, far_image.get_size(), near_image.get_size())
	var atlas_data := str((atlas_value as Dictionary).get("atlas_data", "")) + "\n" + _extra_atlas_data(far_image, near_image)
	if not _validate_in_memory(skeleton, atlas_data):
		return false
	if not _make_dir(output_root):
		return false

	for copy_pair: Array in [
		[str(inputs.base_page), output_root.path_join(BASE_PAGE)],
		[str(inputs.death_page), output_root.path_join(DEATH_PAGE)],
		[str(inputs.head_page), output_root.path_join(HEAD_PAGE)],
		[str(inputs.far_thigh), output_root.path_join(FAR_THIGH_PAGE)],
		[str(inputs.near_thigh), output_root.path_join(NEAR_THIGH_PAGE)],
	]:
		if DirAccess.copy_absolute(str(copy_pair[0]), str(copy_pair[1])) != OK:
			return _set_error("Could not copy input page: %s" % copy_pair[0])
	var graybox := _build_graybox_page()
	if graybox.save_png(output_root.path_join(GRAYBOX_PAGE)) != OK:
		return _set_error("Could not save diagnostic graybox page")
	if not _write_text(output_root.path_join(SEM_OUTPUT_JSON), JSON.stringify(skeleton, "  ", false) + "\n"):
		return false
	var atlas_wrapper := {
		"atlas_data": atlas_data,
		"normal_texture_prefix": "n",
		"source_path": "%s/%s" % [RESOURCE_ROOT, SEM_OUTPUT_ATLAS.replace(".spatlas", ".atlas")],
		"specular_texture_prefix": "s",
	}
	if not _write_text(output_root.path_join(SEM_OUTPUT_ATLAS), JSON.stringify(atlas_wrapper, "", false) + "\n"):
		return false
	if not _write_text(output_root.path_join(SEM_OUTPUT_DATA), _build_tres()):
		return false
	if not _write_text(output_root.path_join(SEM_OUTPUT_MANIFEST), JSON.stringify(_build_manifest(inputs), "  ", false) + "\n"):
		return false
	print("Built fail-closed semantic_split_v3 A/B candidate: %s" % output_root)
	print("  real: 0031 + 0045 + 0033 + 0030 head stack, 0078/0083 thighs")
	print("  gray proxies: torso/coordinated skirt group, both arms, both lower-leg+boot unions")
	print("  explicitly absent: four production skirt slots and far-shoulder ornament back/front")
	print("  deployable: false")
	return true


func _load_rgba(path: String, label: String) -> Image:
	var image := Image.load_from_file(path)
	if image == null or image.is_empty():
		_set_error("Could not decode %s" % label)
		return Image.new()
	if image.get_format() != Image.FORMAT_RGBA8:
		_set_error("%s must decode natively as RGBA8" % label)
		return Image.new()
	for corner: Vector2i in [Vector2i.ZERO, Vector2i(image.get_width() - 1, 0), Vector2i(0, image.get_height() - 1), image.get_size() - Vector2i.ONE]:
		if image.get_pixelv(corner).a8 != 0:
			_set_error("%s must retain four transparent corners" % label)
			return Image.new()
	return image


func _patch_skeleton(skeleton: Dictionary, far_size: Vector2i, near_size: Vector2i) -> void:
	skeleton["skeleton"]["hash"] = "vivhite-semantic-split-v3-fail-closed"
	var bones_by_name := {}
	for bone_value: Variant in skeleton["bones"]:
		var bone: Dictionary = bone_value
		bones_by_name[str(bone["name"])] = bone
	var far_target := Vector2(float(bones_by_name["vivhite_knee_left"]["x"]), float(bones_by_name["vivhite_knee_left"]["y"]))
	var near_target := Vector2(float(bones_by_name["vivhite_knee_right"]["x"]), float(bones_by_name["vivhite_knee_right"]["y"]))
	var far_thigh := _fitted_region_attachment(REGION_FAR_THIGH, far_size, FAR_THIGH_SOURCE_START, FAR_THIGH_SOURCE_END, far_target)
	var near_thigh := _fitted_region_attachment(REGION_NEAR_THIGH, near_size, NEAR_THIGH_SOURCE_START, NEAR_THIGH_SOURCE_END, near_target)

	var region_attachments := {
		REGION_FAR_THIGH: far_thigh,
		REGION_NEAR_THIGH: near_thigh,
		REGION_GRAY_FAR_LOWERBOOT: _limb_region(REGION_GRAY_FAR_LOWERBOOT, Vector2(float(bones_by_name["vivhite_ankle_left"]["x"]), float(bones_by_name["vivhite_ankle_left"]["y"])), 52.0, 72.0),
		REGION_GRAY_NEAR_LOWERBOOT: _limb_region(REGION_GRAY_NEAR_LOWERBOOT, Vector2(float(bones_by_name["vivhite_ankle_right"]["x"]), float(bones_by_name["vivhite_ankle_right"]["y"])), 58.0, 78.0),
		REGION_GRAY_FAR_UPPER: {"path": REGION_GRAY_FAR_UPPER, "x": -28.4795169830322, "y": -55.9500007629395, "rotation": -116.976879650387, "width": 205.0, "height": 58.0},
		REGION_GRAY_FAR_FOREARM: {"path": REGION_GRAY_FAR_FOREARM, "x": -58.8318023681641, "y": -59.0191841125488, "rotation": -134.908899278473, "width": 250.0, "height": 104.0},
		REGION_GRAY_NEAR_UPPER: _limb_region(REGION_GRAY_NEAR_UPPER, Vector2(float(bones_by_name["vivhite_forearm_right"]["x"]), float(bones_by_name["vivhite_forearm_right"]["y"])), 18.0, 62.0),
		REGION_GRAY_NEAR_FOREARM: _limb_region(REGION_GRAY_NEAR_FOREARM, Vector2(float(bones_by_name["vivhite_hand_right"]["x"]), float(bones_by_name["vivhite_hand_right"]["y"])), 42.0, 104.0),
		REGION_GRAY_TORSO: {"path": REGION_GRAY_TORSO, "x": 4.0, "y": -54.0, "rotation": 0.0, "width": 250.0, "height": 282.0},
		REGION_GRAY_SKIRT: {"path": REGION_GRAY_SKIRT, "x": 0.0, "y": -116.0, "rotation": 0.0, "width": 318.0, "height": 268.0},
	}

	for slot_value: Variant in skeleton["slots"]:
		var slot: Dictionary = slot_value
		var name := str(slot["name"])
		if PART_ATTACHMENTS.has(name):
			var attachment_name := str(PART_ATTACHMENTS[name])
			if attachment_name.is_empty():
				slot.erase("attachment")
			else:
				slot["attachment"] = attachment_name
		elif DEATH_ATTACHMENTS.has(name):
			slot.erase("attachment")

	var skin: Dictionary = skeleton["skins"][0]
	var attachments: Dictionary = skin["attachments"]
	for slot_name: String in PART_ATTACHMENTS:
		var attachment_name := str(PART_ATTACHMENTS[slot_name])
		attachments[slot_name] = {}
		if not attachment_name.is_empty():
			attachments[slot_name][attachment_name] = (region_attachments[attachment_name] as Dictionary).duplicate(true)
	for slot_name: String in DEATH_ATTACHMENTS:
		var death_name := str(DEATH_ATTACHMENTS[slot_name])
		attachments[slot_name] = {}
		if not death_name.is_empty():
			var source_name := death_name.trim_prefix("death_")
			attachments[slot_name][death_name] = (region_attachments[source_name] as Dictionary).duplicate(true)

	_reorder_slots(skeleton)
	_patch_visibility_timelines(skeleton)


func _fitted_region_attachment(region: String, source_size: Vector2i, source_start: Vector2, source_end: Vector2, target_end: Vector2) -> Dictionary:
	var source_center := Vector2(source_size) * 0.5
	var source_start_up := Vector2(source_start.x - source_center.x, source_center.y - source_start.y)
	var source_end_up := Vector2(source_end.x - source_center.x, source_center.y - source_end.y)
	var source_axis := source_end_up - source_start_up
	var scale := target_end.length() / source_axis.length()
	var rotation := target_end.angle() - source_axis.angle()
	var center := -source_start_up.rotated(rotation) * scale
	return {
		"path": region,
		"x": center.x,
		"y": center.y,
		"rotation": rad_to_deg(rotation),
		"width": float(source_size.x) * scale,
		"height": float(source_size.y) * scale,
	}


func _limb_region(region: String, target_end: Vector2, distal_extension: float, thickness: float) -> Dictionary:
	var unit := target_end.normalized()
	return {
		"path": region,
		"x": unit.x * (target_end.length() * 0.5 + distal_extension * 0.5),
		"y": unit.y * (target_end.length() * 0.5 + distal_extension * 0.5),
		"rotation": rad_to_deg(target_end.angle()),
		"width": target_end.length() + distal_extension,
		"height": thickness,
	}


func _reorder_slots(skeleton: Dictionary) -> void:
	var slots_by_name := {}
	for slot_value: Variant in skeleton["slots"]:
		var slot: Dictionary = slot_value
		slots_by_name[str(slot["name"])] = slot
	var order: Array[String] = [
		"vivhite_magic_sigil",
		"part_leg_left_lower", "death_leg_left_lower", "part_leg_left_thigh", "death_leg_left_thigh", "part_leg_left_foot", "death_leg_left_foot",
		"part_leg_right_lower", "death_leg_right_lower", "part_leg_right_thigh", "death_leg_right_thigh", "part_leg_right_foot", "death_leg_right_foot",
		"part_arm_left_upper", "death_arm_left_upper", "part_arm_left_forearm", "death_arm_left_forearm", "part_arm_left_hand", "death_arm_left_hand",
		"semantic_back_hair",
		"part_skirt", "death_skirt", "part_torso", "death_torso",
		"semantic_head_face", "semantic_butterfly", "semantic_front_hair",
		"part_arm_right_upper", "death_arm_right_upper", "part_arm_right_forearm", "death_arm_right_forearm", "part_arm_right_hand", "death_arm_right_hand",
		"vivhite_death_body", "slash_mesh", "eye_attach_slot",
	]
	var reordered: Array = []
	for name: String in order:
		if slots_by_name.has(name):
			reordered.append(slots_by_name[name])
	skeleton["slots"] = reordered


func _patch_visibility_timelines(skeleton: Dictionary) -> void:
	for animation_name: String in REQUIRED_ANIMATIONS:
		var animation: Dictionary = skeleton["animations"][animation_name]
		if not animation.has("slots"):
			animation["slots"] = {}
		var timelines: Dictionary = animation["slots"]
		if animation_name == "die":
			for slot_name: String in PART_ATTACHMENTS:
				timelines[slot_name] = {"attachment": [{"time": 0.0}]}
			for slot_name: String in DEATH_ATTACHMENTS:
				var name := str(DEATH_ATTACHMENTS[slot_name])
				var keys: Array = [{"time": 0.0}]
				if not name.is_empty():
					keys[0]["name"] = name
				keys.append({"time": 1.05})
				timelines[slot_name] = {"attachment": keys}
		else:
			for slot_name: String in PART_ATTACHMENTS:
				var name := str(PART_ATTACHMENTS[slot_name])
				var keys: Array = [{"time": 0.0}]
				if not name.is_empty():
					keys[0]["name"] = name
				if animation_name == "relaxed_loop":
					var tail := {"time": 12.000001}
					if not name.is_empty():
						tail["name"] = name
					keys.append(tail)
				timelines[slot_name] = {"attachment": keys}
			for slot_name: String in DEATH_ATTACHMENTS:
				var keys: Array = [{"time": 0.0}]
				if animation_name == "relaxed_loop":
					keys.append({"time": 12.000001})
				timelines[slot_name] = {"attachment": keys}


func _build_graybox_page() -> Image:
	var page := Image.create(1024, 1024, false, Image.FORMAT_RGBA8)
	page.fill(Color(0, 0, 0, 0))
	for region_name: String in GRAY_REGIONS:
		var rect: Rect2i = GRAY_REGIONS[region_name]
		_draw_diagnostic_region(page, rect, region_name)
	return page


func _draw_diagnostic_region(page: Image, rect: Rect2i, region_name: String) -> void:
	var base := Color("d84b9b") if "arm" in region_name else Color("d6b93d")
	if "lower_leg" in region_name:
		base = Color("44a7ba")
	var border := Color("321a35")
	for y in range(rect.position.y, rect.end.y):
		for x in range(rect.position.x, rect.end.x):
			var lx := x - rect.position.x
			var ly := y - rect.position.y
			var inside := true
			if "skirt" in region_name:
				var inset := int(round(float(ly) / float(rect.size.y) * 36.0))
				inside = lx >= inset and lx < rect.size.x - inset
			elif "lower_leg" in region_name:
				inside = ly >= 24 and ly < rect.size.y - 24
				if lx > rect.size.x - 88:
					inside = ly >= 12 and ly < rect.size.y - 12
			elif "arm" in region_name:
				inside = ly >= 12 and ly < rect.size.y - 12
			if not inside:
				continue
			var edge := lx < 4 or ly < 4 or lx >= rect.size.x - 4 or ly >= rect.size.y - 4
			var hatch := ((lx + ly) % 28) < 3 or ((lx - ly + 2048) % 28) < 3
			page.set_pixel(x, y, border if edge or hatch else base)


func _extra_atlas_data(far_image: Image, near_image: Image) -> String:
	var lines: Array[String] = [
		"%s" % GRAYBOX_PAGE,
		"size:1024,1024", "filter:Linear,Linear", "pma:false", "repeat:none",
	]
	for region_name: String in GRAY_REGIONS:
		var rect: Rect2i = GRAY_REGIONS[region_name]
		lines.append(region_name)
		lines.append("bounds:%d,%d,%d,%d" % [rect.position.x, rect.position.y, rect.size.x, rect.size.y])
	lines.append("")
	lines.append_array([
		FAR_THIGH_PAGE, "size:%d,%d" % [far_image.get_width(), far_image.get_height()],
		"filter:Linear,Linear", "pma:false", "repeat:none", REGION_FAR_THIGH,
		"bounds:0,0,%d,%d" % [far_image.get_width(), far_image.get_height()], "",
		NEAR_THIGH_PAGE, "size:%d,%d" % [near_image.get_width(), near_image.get_height()],
		"filter:Linear,Linear", "pma:false", "repeat:none", REGION_NEAR_THIGH,
		"bounds:0,0,%d,%d" % [near_image.get_width(), near_image.get_height()], "",
	])
	return "\n".join(lines)


func _build_tres() -> String:
	var lines := PackedStringArray([
		"[gd_resource type=\"SpineSkeletonDataResource\" load_steps=13 format=3]",
		"",
		"[ext_resource type=\"SpineAtlasResource\" path=\"%s/%s\" id=\"1_atlas\"]" % [RESOURCE_ROOT, SEM_OUTPUT_ATLAS],
		"[ext_resource type=\"SpineSkeletonFileResource\" path=\"%s/%s\" id=\"2_skeleton\"]" % [RESOURCE_ROOT, SEM_OUTPUT_JSON],
	])
	var mix_ids := PackedStringArray()
	for contract: Dictionary in SPLIT_ANIMATION_MIXES:
		var mix_id := str(contract["id"])
		mix_ids.append("SubResource(\"%s\")" % mix_id)
		lines.append("")
		lines.append("[sub_resource type=\"SpineAnimationMix\" id=\"%s\"]" % mix_id)
		lines.append("from = \"%s\"" % contract["from"])
		lines.append("to = \"%s\"" % contract["to"])
		var mix := float(contract["mix"])
		if not is_zero_approx(mix):
			lines.append("mix = %s" % str(mix))
	lines.append("")
	lines.append("[resource]")
	lines.append("atlas_res = ExtResource(\"1_atlas\")")
	lines.append("skeleton_file_res = ExtResource(\"2_skeleton\")")
	lines.append("default_mix = 0.05")
	lines.append("animation_mixes = [%s]" % ", ".join(mix_ids))
	return "\n".join(lines) + "\n"


func _validate_in_memory(skeleton: Dictionary, atlas_data: String) -> bool:
	if str(skeleton.get("skeleton", {}).get("spine", "")) != "4.2.43":
		return _set_error("Semantic split candidate must remain Spine 4.2.43")
	for animation_name: String in REQUIRED_ANIMATIONS:
		if not skeleton.get("animations", {}).has(animation_name):
			return _set_error("Missing animation %s" % animation_name)
	for event_name: String in SEM_REQUIRED_EVENTS:
		if not skeleton.get("events", {}).has(event_name):
			return _set_error("Missing event %s" % event_name)
	for marker: String in [REGION_FAR_THIGH, REGION_NEAR_THIGH, REGION_GRAY_TORSO, REGION_GRAY_NEAR_FOREARM]:
		if not atlas_data.contains("\n%s\n" % marker):
			return _set_error("Atlas is missing region %s" % marker)
	var slot_names: Array[String] = []
	for slot_value: Variant in skeleton["slots"]:
		slot_names.append(str(slot_value["name"]))
	for required_slot: String in ["slash_mesh", "eye_attach_slot", "semantic_back_hair", "semantic_head_face", "semantic_front_hair", "semantic_butterfly"]:
		if required_slot not in slot_names:
			return _set_error("Missing slot %s" % required_slot)
	if slot_names.find("semantic_butterfly") > slot_names.find("semantic_front_hair"):
		return _set_error("Dedicated butterfly evidence requires butterfly behind front hair")
	return true


func _build_manifest(inputs: Dictionary) -> Dictionary:
	return {
		"schema": "vivhite-semantic-split-v3/v1",
		"name": "semantic_split_v3",
		"status": "fail_closed_cross_component_graybox_not_deployable",
		"deployable": false,
		"runtime_skin_modified": false,
		"paid_generation_calls": 0,
		"ab_contract": {
			"A": "legacy split_mesh motion consumer; temporary flattened-UV art",
			"B": "semantic_split_v3 real eligible attachments plus explicit missing-art grayboxes",
			"scene_scale": 0.28,
			"authored_character_scale": 0.70,
			"animations": REQUIRED_ANIMATIONS,
			"dense_samples_per_animation": 21,
		},
		"component_slots": [
			{"group": "back_hair", "slot": "semantic_back_hair", "state": "real_research_art_dynamic_component_passed_pending_total_rig", "source": "0031"},
			{"group": "head_face", "slot": "semantic_head_face", "state": "real_research_art_pending_total_rig", "source": "0045"},
			{"group": "head_face", "slot": "semantic_front_hair", "state": "real_research_art_pending_total_rig", "source": "0033"},
			{"group": "butterfly", "slot": "semantic_butterfly", "state": "real_art_component_vulkan_passed_pending_total_rig", "source": "0030"},
			{"group": "torso_skirt", "slot": "part_torso", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_TORSO},
			{"group": "torso_skirt", "slot": "part_skirt", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_SKIRT},
			{"group": "left_arm", "slot": "part_arm_left_upper", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_FAR_UPPER},
			{"group": "left_arm", "slot": "part_arm_left_forearm", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_FAR_FOREARM},
			{"group": "right_arm", "slot": "part_arm_right_upper", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_NEAR_UPPER},
			{"group": "right_arm", "slot": "part_arm_right_forearm", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_NEAR_FOREARM},
			{"group": "left_leg", "slot": "part_leg_left_thigh", "state": "real_static_research_only", "source": "0078"},
			{"group": "left_leg", "slot": "part_leg_left_lower", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_FAR_LOWERBOOT},
			{"group": "right_leg", "slot": "part_leg_right_thigh", "state": "real_static_research_only", "source": "0083"},
			{"group": "right_leg", "slot": "part_leg_right_lower", "state": "requires_new_evolink_semantic_generation", "graybox": REGION_GRAY_NEAR_LOWERBOOT},
		],
		"production_slot_contract": [
			{"group": "back_hair", "slot": "semantic_back_hair", "state": "real_research_art_dynamic_component_passed_pending_total_rig", "source": "0031"},
			{"group": "head_face", "slot": "semantic_head_face", "state": "real_research_art_pending_total_rig", "source": "0045"},
			{"group": "head_face", "slot": "semantic_front_hair", "state": "real_research_art_pending_total_rig", "source": "0033"},
			{"group": "butterfly", "slot": "semantic_butterfly", "state": "real_art_component_vulkan_passed_pending_total_rig", "source": "0030"},
			{"group": "torso_skirt", "slot": "torso_core", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_torso"},
			{"group": "torso_skirt", "slot": "skirt_back", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_skirt"},
			{"group": "torso_skirt", "slot": "skirt_side_far", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_skirt"},
			{"group": "torso_skirt", "slot": "skirt_center_front", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_skirt"},
			{"group": "torso_skirt", "slot": "skirt_side_near", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_skirt"},
			{"group": "torso_skirt", "slot": "far_shoulder_ornament_back", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "explicitly_absent_no_fake_attachment"},
			{"group": "torso_skirt", "slot": "far_shoulder_ornament_front", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "explicitly_absent_no_fake_attachment"},
			{"group": "left_arm", "slot": "far_upper_arm_and_sleeve", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_arm_left_upper"},
			{"group": "left_arm", "slot": "far_forearm_hand", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_arm_left_forearm"},
			{"group": "right_arm", "slot": "near_upper_arm_and_sleeve", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_arm_right_upper"},
			{"group": "right_arm", "slot": "near_forearm_hand", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_arm_right_forearm"},
			{"group": "left_leg", "slot": "far_thigh", "state": "real_static_research_only", "source": "0078", "rendered_proxy": "part_leg_left_thigh"},
			{"group": "left_leg", "slot": "far_lower_leg_with_boot", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_leg_left_lower"},
			{"group": "right_leg", "slot": "near_thigh", "state": "real_static_research_only", "source": "0083", "rendered_proxy": "part_leg_right_thigh"},
			{"group": "right_leg", "slot": "near_lower_leg_with_boot", "state": "requires_new_evolink_semantic_generation", "rendered_proxy": "part_leg_right_lower"},
		],
		"production_runtime_ready_slots": [],
		"art_or_component_candidates_ready_for_total_gate": ["semantic_back_hair", "semantic_butterfly"],
		"research_only_slots": ["semantic_head_face", "semantic_front_hair", "part_leg_left_thigh", "part_leg_right_thigh"],
		"new_evolink_semantic_generation_required": [
			"torso_core", "skirt_back", "skirt_side_far", "skirt_center_front", "skirt_side_near",
			"far_shoulder_ornament_back", "far_shoulder_ornament_front",
			"far_upper_arm_and_sleeve", "far_forearm_hand",
			"near_upper_arm_and_sleeve", "near_forearm_hand",
			"far_lower_leg_with_boot", "near_lower_leg_with_boot",
		],
		"topology_contract": {
			"far_arm": "far_upper_arm_and_sleeve + far_forearm_hand; wrist is measurement-only; no slash_mesh ownership",
			"near_arm": "near_upper_arm_and_sleeve + near_forearm_hand; wrist is measurement-only; slash_mesh remains a separate VFX consumer",
			"far_leg": "far_thigh + far_lower_leg_with_boot; preserve knee, remove separate ankle attachment",
			"near_leg": "near_thigh + near_lower_leg_with_boot; preserve knee, remove separate ankle attachment",
			"skirt": "skirt_back + skirt_side_far + skirt_center_front + skirt_side_near, generated as one coordinated costume group but stored as separate attachments",
			"far_shoulder": "far_shoulder_ornament_back < far_upper_arm_and_sleeve < far_shoulder_ornament_front",
		},
		"layer_order_correction": {
			"old_head_face_candidate": "back -> torso -> head -> front_hair -> butterfly",
			"integrated_order": "far limbs -> back_hair -> skirt -> torso -> head_face -> butterfly -> front_hair -> near arm",
			"evidence": "Dedicated butterfly 16/16 Vulkan A/B showed the connector must sit behind front hair; head-face component accepted this correction.",
		},
		"source_hashes": {
			"head_page": FileAccess.get_sha256(str(inputs.head_page)).to_lower(),
			"head_spjson": FileAccess.get_sha256(str(inputs.head_json)).to_lower(),
			"far_thigh_0078": FileAccess.get_sha256(str(inputs.far_thigh)).to_lower(),
			"near_thigh_0083": FileAccess.get_sha256(str(inputs.near_thigh)).to_lower(),
		},
		"known_limits": [
			"Diagnostic grayboxes are not Bai Qi art and are intentionally conspicuous.",
			"The one rendered skirt proxy only proves gross cross-component motion; it does not claim that the required four skirt attachments exist or passed their independent +/-46 degree gate.",
			"Far-shoulder ornament back/front are deliberately absent from the render and explicitly blocked, rather than faked with the arm or torso proxy.",
			"0078 and 0083 are static research thighs, not production-approved runtime attachments.",
			"The existing dedicated death body remains an external transition reference; this assembly does not claim to fix its landing jump.",
			"No result from this candidate may be copied into Vivhite/Vivhite/skins/ironclad.",
		],
	}
